version: 0.2

env:
  variables:
    NCP_CR_URL: "cuecode.kr.ncr.ntruss.com"
  parameter-store:
    KUBECONFIG_B64: "/my-app/kubeconfig-b64"

phases:
  install:
    commands:
      - echo "Installing ncp-iam-authenticator..."
      - curl -o ncp-iam-authenticator -L https://github.com/NaverCloudPlatform/ncp-iam-authenticator/releases/latest/download/ncp-iam-authenticator_linux_amd64
      - chmod +x ./ncp-iam-authenticator
      - mv ./ncp-iam-authenticator /usr/local/bin/
      - echo "Logging in to Naver Cloud Container Registry..."
      - docker login -u ${NCP_CR_ACCESS_KEY_ID} -p ${NCP_CR_SECRET_KEY} ${NCP_CR_URL}

  pre_build:
    commands:
      - echo "Setting image tag..."
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - echo "Using Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building and pushing all service images..."
      - docker build -t ${NCP_CR_URL}/api-gateway:${IMAGE_TAG} ./ApiGateway
      - docker push ${NCP_CR_URL}/api-gateway:${IMAGE_TAG}
      - docker build -t ${NCP_CR_URL}/front-ui:${IMAGE_TAG} ./FrontUI
      - docker push ${NCP_CR_URL}/front-ui:${IMAGE_TAG}
      - docker build -t ${NCP_CR_URL}/motion-service:${IMAGE_TAG} ./MotionService
      - docker push ${NCP_CR_URL}/motion-service:${IMAGE_TAG}
      - docker build -t ${NCP_CR_URL}/config-server:${IMAGE_TAG} ./SpringConfigServer
      - docker push ${NCP_CR_URL}/config-server:${IMAGE_TAG}
      - docker build -t ${NCP_CR_URL}/user-service:${IMAGE_TAG} ./UserService
      - docker push ${NCP_CR_URL}/user-service:${IMAGE_TAG}
      - docker build -t ${NCP_CR_URL}/cuecode-motion:${IMAGE_TAG} ./CueCodeMotion
      - docker push ${NCP_CR_URL}/cuecode-motion:${IMAGE_TAG}

  post_build:
    commands:
      - echo "Updating all deployment YAMLs..."
      - sed -i "s|image:.*|image: ${NCP_CR_URL}/api-gateway:${IMAGE_TAG}|" ./ApiGateway/k8s/deployment.yaml
      - sed -i "s|image:.*|image: ${NCP_CR_URL}/front-ui:${IMAGE_TAG}|" ./FrontUI/k8s/deployment.yaml
      - sed -i "s|image:.*|image: ${NCP_CR_URL}/motion-service:${IMAGE_TAG}|" ./MotionService/k8s/deployment.yaml
      - sed -i "s|image:.*|image: ${NCP_CR_URL}/config-server:${IMAGE_TAG}|" ./SpringConfigServer/k8s/deployment.yaml
      - sed -i "s|image:.*|image: ${NCP_CR_URL}/user-service:${IMAGE_TAG}|" ./UserService/k8s/deployment.yaml
      - sed -i "s|image:.*|image: ${NCP_CR_URL}/cuecode-motion:${IMAGE_TAG}|" ./CueCodeMotion/k8s/deployment.yaml

artifacts:
  files:
    - '**/*/k8s/*.yaml'
  discard-paths: yes